apiVersion: apps/v1
kind: Deployment
metadata:
  name: nblotti-delos
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scheme: "http"
  labels:
    app: nblotti_delos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nblotti_delos
  template:
    metadata:
      labels:
        app: nblotti_delos
    spec:
      containers:
        - name: nblotti
          image: nblotti/delos:v0.0.126
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 1
            periodSeconds: 30
      imagePullSecrets:
        - name: regcred
