drop SEQUENCE IF EXISTS hibernate_sequence CASCADE;
CREATE SEQUENCE hibernate_sequence START 20000000;

drop FUNCTION IF EXISTS refresh_fn CASCADE;
drop PROCEDURE IF EXISTS refresh_fn CASCADE;

CREATE PROCEDURE refresh_fn()
LANGUAGE PLPGSQL
AS $$
BEGIN
   REFRESH MATERIALIZED VIEW SP_500_BY_SECTOR_INDUSTRY_DATE;
   REFRESH MATERIALIZED VIEW SP_500_BY_SECTOR_DATE;
END;
$$;



